title: "Personal and Academic Webpage Editing"
author: "Alex Sampson"
description: "Florida State University"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter
mathjax: true                   # allows renderable LaTeX. Uses: $$ inline math $$

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}

  - {file: "index.md", title: "About Me", sidebaricon: profile}
  - {file: "archive.html", title: "Archive", sidebaricon: box}
  - {file: "README.md", title: "README.md"}
  - {file: "blog.html", title: "Blog", sidebaricon: pen-nib}
  - {file: "Alex.pdf", title: "CV", sidebaricon: suitcase}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: E-Mail Me!, icon: envelope, url: "ajsampson@fsu.edu"}
  - {title: Github, icon: github, url: "https://github.com/alex-sampson"}
  #- {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
